# Generated by Django 5.0.14 on 2026-10-04 13:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('selection', '0016_ruche_couleur'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationVisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_observation', models.CharField(choices=[('ESSAIMAGE', 'Colonie essaimée'), ('REINE_MORTE', 'Reine morte'), ('PILLAGE', 'Pillage'), ('FRELONS', 'Frelons')], max_length=20)),
                ('certitude', models.CharField(choices=[('CONSTATE', 'Constaté'), ('DOUTE', 'Doute')], max_length=20)),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('CONFIRMEE', 'Confirmée'), ('INFIRMEE', 'Infirmée')], default='OUVERTE', max_length=20)),
                ('reponse_cellules_royales', models.CharField(blank=True, choices=[('TOUTES_SAUF_UNE', 'Toutes supprimées sauf une'), ('TOUTES', 'Toutes supprimées'), ('PAS_ENCORE', 'Pas encore supprimées')], help_text="Pour une observation d'essaimage uniquement.", max_length=20)),
                ('colonie', models.ForeignKey(help_text="Dénormalisé depuis la visite, pour retrouver directement les observations ouvertes d'une colonie.", on_delete=django.db.models.deletion.CASCADE, related_name='observations_visite', to='selection.colonie')),
            ],
            options={
                'verbose_name': 'Observation de visite',
                'verbose_name_plural': 'Observations de visite',
                'ordering': ['-visite__date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RappelRevisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_revisite', models.DateField()),
                ('traite', models.BooleanField(default=False)),
                ('observation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rappel', to='gestion.observationvisite')),
            ],
            options={
                'verbose_name': 'Rappel de revérification',
                'verbose_name_plural': 'Rappels de revérification',
                'ordering': ['date_revisite'],
            },
        ),
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('observation_reine', models.CharField(blank=True, choices=[('VUE', 'Vue'), ('OEUFS_VUS', 'Œufs vus'), ('RIEN_VU', 'Rien vu')], max_length=20)),
                ('nb_cadres_couvain', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('nb_cadres_abeilles', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reserves', models.CharField(blank=True, choices=[('FAIBLES', 'Faibles'), ('CORRECTES', 'Correctes'), ('BONNES', 'Bonnes')], max_length=20)),
                ('comportement', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Calme'), (2, 'Normale'), (3, 'Nerveuse'), (4, 'Agressive')], null=True)),
                ('notes', models.TextField(blank=True)),
                ('colonie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites', to='selection.colonie')),
            ],
            options={
                'verbose_name': 'Visite',
                'verbose_name_plural': 'Visites',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='observationvisite',
            name='visite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='gestion.visite'),
        ),
        migrations.CreateModel(
            name='ActionVisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('HAUSSE_AJOUTEE', 'Hausse ajoutée'), ('HAUSSE_RETIREE', 'Hausse retirée'), ('NOURRISSEMENT', 'Nourrissement'), ('TRAITEMENT', 'Traitement'), ('SUPPRESSION_CR', 'Suppression des cellules royales')], max_length=20)),
                ('visite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='gestion.visite')),
            ],
            options={
                'verbose_name': 'Action de visite',
                'verbose_name_plural': 'Actions de visite',
            },
        ),
    ]
