# Generated by Django 5.0.14 on 2026-08-26 16:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampagneElevage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('annee', models.PositiveIntegerField()),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': "Campagne d'élevage",
                'verbose_name_plural': "Campagnes d'élevage",
                'ordering': ['-annee', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Colonie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_creation', models.CharField(choices=[('ACHAT', 'Achat'), ('ESSAIMAGE_NATUREL', 'Essaimage naturel'), ('ESSAIM_ARTIFICIEL', 'Essaim artificiel'), ('ORIGINE_INCONNUE', 'Origine inconnue')], max_length=20)),
                ('date_creation', models.DateField()),
                ('active', models.BooleanField(default=True, help_text="Décoché si la colonie n'existe plus (mortalité, réunion avec une autre colonie...).")),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Colonie',
                'verbose_name_plural': 'Colonies',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='CritereSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('type_mesure', models.CharField(choices=[('PASSE_RAPIDE', 'Passe rapide'), ('PASSE_APPROFONDIE', 'Passe approfondie')], max_length=20)),
                ('unite', models.CharField(blank=True, help_text='Unité de la valeur brute (kg, dm², min...), si applicable.', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text="Ordre d'affichage dans les tableaux/fiches.")),
            ],
            options={
                'verbose_name': 'Critère de sélection',
                'verbose_name_plural': 'Critères de sélection',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Ruche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ruche', models.CharField(choices=[('DADANT10', 'Dadant 10'), ('RUCHETTE6', 'Ruchette 6'), ('APIDEA', 'Apidea'), ('DH', 'DH (double haussette)')], max_length=20)),
                ('numero', models.PositiveIntegerField()),
                ('actif', models.BooleanField(default=True, help_text="Décoché si la boîte est retirée du service (cassée, remplacée...). Permet la réutilisation du numéro pour les types Apidea/DH sans supprimer l'historique.")),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Ruche',
                'verbose_name_plural': 'Ruches',
                'ordering': ['type_ruche', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Rucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('localisation', models.CharField(blank=True, help_text='Adresse ou description libre du lieu.', max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Rucher',
                'verbose_name_plural': 'Ruchers',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='StationFecondation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('lieu', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Station de fécondation',
                'verbose_name_plural': 'Stations de fécondation',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationColonie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('nb_corps', models.PositiveSmallIntegerField(default=1)),
                ('nb_hausses', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('colonie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='selection.colonie')),
            ],
            options={
                'verbose_name': 'Configuration de colonie',
                'verbose_name_plural': 'Configurations de colonie',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mesure', models.DateField()),
                ('valeur_brute', models.CharField(help_text='Valeur brute relevée sur le terrain (numérique ou descriptive selon le critère).', max_length=100)),
                ('score', models.PositiveSmallIntegerField(blank=True, help_text="Score 1-4 calculé selon le barème du cours (non calculé automatiquement pour l'instant).", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('notes', models.TextField(blank=True)),
                ('campagne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesures', to='selection.campagneelevage')),
                ('colonie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures', to='selection.colonie')),
                ('critere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mesures', to='selection.critereselection')),
            ],
            options={
                'verbose_name': 'Mesure',
                'verbose_name_plural': 'Mesures',
                'ordering': ['-date_mesure'],
            },
        ),
        migrations.CreateModel(
            name='PoidsCritere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('seuil_eliminatoire', models.DecimalField(blank=True, decimal_places=2, help_text='Seuil éliminatoire optionnel, indépendant du poids (ex. santé, agressivité).', max_digits=6, null=True)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poids_criteres', to='selection.campagneelevage')),
                ('critere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poids_par_campagne', to='selection.critereselection')),
            ],
            options={
                'verbose_name': 'Poids de critère',
                'verbose_name_plural': 'Poids de critères',
                'ordering': ['campagne', 'critere__ordre'],
            },
        ),
        migrations.CreateModel(
            name='Reine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(help_text='Étiquette libre (ex. R24-03).', max_length=50, unique=True)),
                ('lignee_male_probable', models.CharField(blank=True, help_text='Description libre de la lignée mâle probable (fécondation en vol = probabiliste).', max_length=255)),
                ('couleur_marquage', models.CharField(blank=True, choices=[('BLANC', 'Blanc (années en 1 ou 6)'), ('JAUNE', 'Jaune (années en 2 ou 7)'), ('ROUGE', 'Rouge (années en 3 ou 8)'), ('VERT', 'Vert (années en 4 ou 9)'), ('BLEU', 'Bleu (années en 5 ou 0)')], max_length=10)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('date_deces', models.DateField(blank=True, help_text='Renseigné si la reine est morte ou a été remplacée.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('mere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filles', to='selection.reine')),
                ('station_fecondation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reines', to='selection.stationfecondation')),
            ],
            options={
                'verbose_name': 'Reine',
                'verbose_name_plural': 'Reines',
                'ordering': ['-date_naissance', 'identifiant'],
            },
        ),
        migrations.AddField(
            model_name='colonie',
            name='reine_actuelle',
            field=models.ForeignKey(blank=True, help_text='Reine actuellement à la tête de la colonie.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colonie_dirigee', to='selection.reine'),
        ),
        migrations.CreateModel(
            name='EvenementColonie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type_evenement', models.CharField(choices=[('CREATION', 'Création'), ('DEMENAGEMENT', 'Déménagement'), ('REMERAGE', 'Remérage'), ('DIVISION', 'Division'), ('REUNION', 'Réunion avec une autre colonie'), ('MORTALITE', 'Mortalité'), ('AUTRE', 'Autre')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('colonie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='selection.colonie')),
                ('reine', models.ForeignKey(blank=True, help_text='Nouvelle reine installée, pour un remérage.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='selection.reine')),
                ('ruche_destination', models.ForeignKey(blank=True, help_text='Nouvelle boîte, pour un déménagement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='selection.ruche')),
            ],
            options={
                'verbose_name': 'Événement de colonie',
                'verbose_name_plural': 'Événements de colonie',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='colonie',
            name='ruche',
            field=models.ForeignKey(help_text='Boîte physique actuellement occupée.', on_delete=django.db.models.deletion.PROTECT, related_name='colonies', to='selection.ruche'),
        ),
        migrations.AddField(
            model_name='ruche',
            name='rucher',
            field=models.ForeignKey(blank=True, help_text='Emplacement physique actuel de la boîte.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ruches', to='selection.rucher'),
        ),
        migrations.AddConstraint(
            model_name='poidscritere',
            constraint=models.UniqueConstraint(fields=('campagne', 'critere'), name='unique_poids_par_campagne'),
        ),
    ]
