# Generated by Django 5.0.14 on 2026-08-27 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0005_peupler_criteres_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='campagneelevage',
            name='date_reference',
            field=models.DateField(blank=True, help_text="Date de ponte servant de point de départ (jour 0) au calcul en cascade des étapes du calendrier d'élevage (cf. EtapeCalendrier). La renseigner ou la modifier recalcule automatiquement toutes les dates prévues.", null=True),
        ),
        migrations.CreateModel(
            name='EtapeCalendrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_etape', models.CharField(choices=[('ELEVAGE_MALES', 'Élevage des mâles (saturation)'), ('PICKING', 'Picking (greffage des larves)'), ('STARTER', 'Starter'), ('FINISSEUR', 'Finisseur'), ('COUVEUSE', 'Couveuse'), ('RUCHETTES', 'Peuplement des ruchettes'), ('LIBERATION', 'Libération des ruchettes'), ('CONTROLE_NAISSANCE', 'Contrôle des naissances'), ('DEBUT_PONTE', 'Début de ponte'), ('CONTROLE_PONTE', 'Contrôle de ponte')], max_length=30)),
                ('date_prevue', models.DateField()),
                ('realisee', models.BooleanField(default=False)),
                ('date_reelle', models.DateField(blank=True, help_text='Date effectivement observée, si différente de la date prévue (pour tracer les écarts).', null=True)),
                ('notes', models.TextField(blank=True)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='selection.campagneelevage')),
            ],
            options={
                'verbose_name': 'Étape de calendrier',
                'verbose_name_plural': 'Étapes de calendrier',
                'ordering': ['date_prevue'],
            },
        ),
        migrations.AddConstraint(
            model_name='etapecalendrier',
            constraint=models.UniqueConstraint(fields=('campagne', 'type_etape'), name='unique_etape_par_campagne'),
        ),
    ]
