# Generated by Django 5.0.14 on 2026-08-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0006_calendrier_elevage_etapecalendrier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colonie',
            name='mode_creation',
            field=models.CharField(choices=[('ACHAT', 'Achat'), ('ESSAIMAGE_NATUREL', 'Essaimage naturel'), ('ESSAIM_ARTIFICIEL', 'Essaim artificiel'), ('FUSION', 'Fusion / Réunion'), ('ORIGINE_INCONNUE', 'Origine inconnue')], max_length=20),
        ),
    ]
