# Generated by Django 5.0.14 on 2026-08-31 17:04

from django.db import migrations, models

# Types d'étape retirés par l'issue #14 (méthode réelle d'Alain) : plus
# de starter/finisseur séparés, de couveuse, de ruchettes, de libération,
# de contrôle des naissances ni des anciennes étapes de ponte.
ANCIENS_TYPES_ETAPE_SUPPRIMES = [
    "STARTER",
    "FINISSEUR",
    "COUVEUSE",
    "RUCHETTES",
    "LIBERATION",
    "CONTROLE_NAISSANCE",
    "DEBUT_PONTE",
    "CONTROLE_PONTE",
]


def supprimer_etapes_avec_anciens_types(apps, schema_editor):
    """Retire les EtapeCalendrier des campagnes réelles créées avec les
    anciens types d'étape (issue #14). Au moment de l'écriture de cette
    migration, aucune CampagneElevage réelle n'a de date_reference
    renseignée (vérifié en base 'apiselect' avant modification) : cette
    opération ne devrait donc supprimer aucune donnée en pratique, mais
    est nécessaire pour ne rien perdre si une campagne a été créée entre
    temps ou sur un autre environnement (ex. apiselect_dev)."""
    EtapeCalendrier = apps.get_model("selection", "EtapeCalendrier")
    EtapeCalendrier.objects.filter(type_etape__in=ANCIENS_TYPES_ETAPE_SUPPRIMES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0007_alter_colonie_mode_creation'),
    ]

    operations = [
        migrations.RunPython(
            supprimer_etapes_avec_anciens_types, migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='campagneelevage',
            name='elevage_males_actif',
            field=models.BooleanField(default=False, help_text="Coché si l'élevage des mâles (saturation) est pratiqué pour cette campagne. Décoché par défaut : avec un nombre de ruches limité, Alain ne le pratique pas encore (issue #14) — l'étape ELEVAGE_MALES n'est créée que si ce champ est coché."),
        ),
        migrations.AlterField(
            model_name='etapecalendrier',
            name='type_etape',
            field=models.CharField(choices=[('ELEVAGE_MALES', 'Élevage des mâles (saturation)'), ('PICKING', 'Picking (greffage des larves)'), ('RUCHE_ORPHELINE', 'Ruche orpheline'), ('GARNIR_APIDEA', 'Garnir les Apidea'), ('CONTROLE_PONTE_GRILLE', 'Contrôle ponte et pose de la grille anti-essaimage')], max_length=30),
        ),
    ]
