# Generated by Django 5.0.14 on 2026-08-31 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0008_refonte_calendrier_methode_alain'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapecalendrier',
            name='nombre_cr',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Nombre de cellules royales — obtenues sur l'étape Ruche orpheline, ou introduites dans les Apidea sur l'étape Garnir les Apidea (même champ générique pour les deux usages selon l'étape).", null=True),
        ),
        migrations.AddField(
            model_name='etapecalendrier',
            name='ruche',
            field=models.ForeignKey(blank=True, help_text='Ruche ayant servi de colonie orpheline (pertinent surtout sur les étapes Orphelinage et Ruche orpheline).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapes_calendrier', to='selection.ruche'),
        ),
        migrations.AlterField(
            model_name='etapecalendrier',
            name='type_etape',
            field=models.CharField(choices=[('ELEVAGE_MALES', 'Élevage des mâles (saturation)'), ('ORPHELINAGE', 'Orphelinage (règle des 9 jours)'), ('PICKING', 'Picking (greffage des larves)'), ('RUCHE_ORPHELINE', 'Ruche orpheline'), ('GARNIR_APIDEA', 'Garnir les Apidea'), ('CONTROLE_PONTE_GRILLE', 'Contrôle ponte et pose de la grille anti-essaimage')], max_length=30),
        ),
    ]
