# Generated by Django 5.0.14 on 2026-09-01 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0011_vue_mesures_completes_lot_criteres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poidscritere',
            name='poids',
            field=models.PositiveSmallIntegerField(help_text="Poids relatif du critère dans le calcul de l'index, de 0 (aucune importance) à 10 (priorité maximale). Seul le ratio entre les poids compte, pas leur valeur absolue.", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
