# Generated by Django 5.0.14 on 2026-09-01 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0012_alter_poidscritere_poids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapecalendrier',
            name='nombre_cr',
        ),
        migrations.RemoveField(
            model_name='etapecalendrier',
            name='ruche',
        ),
        migrations.AddField(
            model_name='etapecalendrier',
            name='ruche_destination',
            field=models.ForeignKey(blank=True, help_text="Ruche de destination — pertinent seulement sur l'étape Picking (colonie orpheline qui reçoit les larves).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapes_calendrier_destination', to='selection.ruche'),
        ),
        migrations.AddField(
            model_name='etapecalendrier',
            name='ruche_origine',
            field=models.ForeignKey(blank=True, help_text="Ruche d'origine selon l'étape : colonie rendue orpheline (Orphelinage), colonie ciblée pour les larves greffées (Picking), Apidea concerné (Contrôle ponte et grille).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapes_calendrier_origine', to='selection.ruche'),
        ),
        migrations.AddField(
            model_name='reine',
            name='date_fecondation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reine',
            name='mode_acquisition',
            field=models.CharField(blank=True, choices=[('ELEVEE', 'Élevée (sur le rucher)'), ('ACHETEE_CR', 'Achetée en cellule royale'), ('ACHETEE_VIERGE', 'Achetée vierge'), ('ACHETEE_FECONDEE', 'Achetée fécondée')], help_text="Élevée sur le rucher, ou achetée (en cellule royale, vierge ou déjà fécondée). Laissé vide sur les reines existantes avant l'introduction de ce champ (issue #25) — à compléter manuellement au besoin.", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reine',
            name='statut',
            field=models.CharField(blank=True, choices=[('VIERGE', 'Vierge'), ('FECONDEE', 'Fécondée')], help_text="Vierge ou fécondée. Laissé vide sur les reines existantes avant l'introduction de ce champ (issue #25) — à compléter manuellement au besoin.", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='etapecalendrier',
            name='type_etape',
            field=models.CharField(choices=[('ELEVAGE_MALES', 'Élevage des mâles (saturation)'), ('ORPHELINAGE', 'Orphelinage (règle des 9 jours)'), ('PICKING', 'Picking (greffage des larves)'), ('GARNIR_APIDEA', 'Garnir les Apidea'), ('CONTROLE_PONTE_GRILLE', 'Contrôle ponte et pose de la grille anti-essaimage')], max_length=30),
        ),
        migrations.CreateModel(
            name='CelluleRoyale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('EN_DEVELOPPEMENT', 'En développement'), ('DEVENUE_REINE', 'Devenue reine'), ('MORTE_AVANT_ECLOSION', 'Morte avant éclosion'), ('PERDUE', 'Perdue')], default='EN_DEVELOPPEMENT', max_length=25)),
                ('notes', models.TextField(blank=True)),
                ('apidea', models.ForeignKey(blank=True, help_text='Apidea où la cellule a été introduite — une seule, jamais plusieurs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cellules_royales_introduites', to='selection.ruche')),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cellules_royales', to='selection.campagneelevage')),
                ('mere', models.ForeignKey(help_text='Reine dont les larves ont été greffées.', on_delete=django.db.models.deletion.PROTECT, related_name='cellules_royales_greffees', to='selection.reine')),
                ('reine', models.ForeignKey(blank=True, help_text='Reine issue de cette cellule — renseignée uniquement si statut=Devenue reine (cf. action admin « Confirmer éclosion »).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cellule_royale_origine', to='selection.reine')),
                ('ruche_orpheline', models.ForeignKey(help_text='Ruche orpheline ayant élevé cette cellule royale.', on_delete=django.db.models.deletion.PROTECT, related_name='cellules_royales_elevees', to='selection.ruche')),
            ],
            options={
                'verbose_name': 'Cellule royale',
                'verbose_name_plural': 'Cellules royales',
                'ordering': ['-campagne__annee', 'campagne__nom', 'mere__identifiant'],
            },
        ),
    ]
