# Generated by Django 5.0.14 on 2026-09-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0013_remove_etapecalendrier_nombre_cr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colonie',
            name='date_creation',
            field=models.DateField(blank=True, help_text="Laisser vide si la date exacte est inconnue (colonie déjà existante avant la reprise de l'élevage, issue #29).", null=True),
        ),
        migrations.AlterField(
            model_name='reine',
            name='mode_acquisition',
            field=models.CharField(blank=True, choices=[('ELEVEE', 'Élevée (sur le rucher)'), ('ACHETEE_CR', 'Achetée en cellule royale'), ('ACHETEE_VIERGE', 'Achetée vierge'), ('ACHETEE_FECONDEE', 'Achetée fécondée'), ('ARRIVEE_ESSAIM', 'Arrivée avec un essaim'), ('REMERAGE_NATUREL', 'Remérage naturel (par la colonie elle-même)')], help_text="Élevée sur le rucher, ou achetée (en cellule royale, vierge ou déjà fécondée). Laissé vide sur les reines existantes avant l'introduction de ce champ (issue #25) — à compléter manuellement au besoin.", max_length=20, null=True),
        ),
    ]
