# Generated by Django 5.0.14 on 2026-09-02 20:16
#
# Issue #31 : Mesure.campagne devient obligatoire (PROTECT, null=False,
# blank=False) pour éviter les mesures invisibles du tableau de résultats
# (qui filtre par campagne). Vérifié avant écriture : aucune Mesure avec
# campagne_id NULL en base 'apiselect' (0 mesure au total) ni en base
# 'apiselect_dev' (2 mesures, aucune avec campagne_id NULL) — l'ALTER
# COLUMN ... SET NOT NULL ne rencontre donc aucune ligne à corriger.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0014_alter_colonie_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesure',
            name='campagne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mesures', to='selection.campagneelevage'),
        ),
    ]
