# Generated by Django 5.0.14 on 2026-10-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0015_mesure_campagne_obligatoire'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruche',
            name='couleur',
            field=models.CharField(blank=True, default='', help_text='Couleur hexadécimale réelle de la ruche telle que peinte (ex. #3f8f3f). Laisser vide si inconnue ou non peinte (issue #41).', max_length=7),
        ),
    ]
