# Generated by Django 5.0.14 on 2026-10-05 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_vendeur'),
        ('selection', '0018_typeruche_hauteur_relative_pourcent'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenementcolonie',
            name='ancienne_reine',
            field=models.ForeignKey(blank=True, help_text='Reine remplacée, pour un remérage (issue #51) — conservée telle quelle, seulement détachée de la colonie.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='selection.reine'),
        ),
        migrations.AddField(
            model_name='reine',
            name='date_marquage',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reine',
            name='marquage_effectue',
            field=models.BooleanField(default=False, help_text="La couleur du marquage (ci-dessus) reste déterminée par l'année de naissance ; ce champ indique si le marquage a été réellement posé (issue #51). Valeur par défaut 'non' sur les reines existantes avant l'introduction de ce champ, à corriger manuellement."),
        ),
        migrations.AddField(
            model_name='reine',
            name='vendeur',
            field=models.ForeignKey(blank=True, help_text='Pour une reine achetée (issue #51).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reines', to='gestion.vendeur'),
        ),
        migrations.AlterField(
            model_name='reine',
            name='mode_acquisition',
            field=models.CharField(blank=True, choices=[('ELEVEE', 'Élevée (sur le rucher)'), ('ACHETEE_CR', 'Achetée en cellule royale'), ('ACHETEE_VIERGE', 'Achetée vierge'), ('ACHETEE_FECONDEE', 'Achetée fécondée'), ('ARRIVEE_ESSAIM', 'Arrivée avec un essaim'), ('REMERAGE_NATUREL', 'Remérage naturel (par la colonie elle-même)'), ('DONNEE', 'Donnée')], help_text="Élevée sur le rucher, ou achetée (en cellule royale, vierge ou déjà fécondée). Laissé vide sur les reines existantes avant l'introduction de ce champ (issue #25) — à compléter manuellement au besoin.", max_length=20, null=True),
        ),
    ]
